### ISSUE TITLE
 syntax error, unexpected tIDENTIFIER

### ISSUE THREAD

**Issue by pdurusau** [yardenac/eml2mbox#8]
Running the script with Ruby ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux], 64-bit Ubuntu 14.04, with the command line:

ruby eml2mbox.rb 

in the directory with the .eml files, no mbox specified, fails with:

*****
eml2mbox.rb:240: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...mbox file. Defaults to "archive.mbox" in 'emlpath'    #
*****

Line 240 reads:

*****
trgtmbx - Name of the target mbox file. Defaults to "archive.mbox" in 'emlpath'
*****

Changing to:

*****
trgtmbx - Name of the target mbox file. Defaults to 'archive.mbox' in 'emlpath'
*****

fixes the issue. 

Now I have file issues to correct but the generation of the mbox appears to be successful.

Thanks! Patrick

**Comment by yardenac** [comment]
Fixed by https://github.com/yardenac/eml2mbox/pull/7
