### ISSUE TITLE
Please allow to work with single .eml files without having to specify a directory

### ISSUE THREAD

**Issue by xtaran** [yardenac/eml2mbox#9]
Calling it with a single `.eml` _file_ as parameter causes the following error to be displayed:

```
[<…>..eml] is not a directory (might not exist). Please specify a valid dir
```

Sometimes it's necessary to only convert a single `.eml` file from a directory with multiple `.eml` files, e.g. if you want to have one mbox per `.eml` file as it's common in forensics.

**Comment by yardenac** [comment]
Alright, I added this option. Let me know if it works for you.
